### Common authentication/login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email": "sriharsha@gmail.com",
    "password": "Swami"
}

### admin blocks user
PUT http://localhost:4000/admin-api/block
Content-Type: application/json

{
    "userEmail": "sriharsha@gmail.com"
}

### admin unblocks user
PUT http://localhost:4000/admin-api/unblock
Content-Type: application/json

{
    "userEmail": "sriharsha@gmail.com"
}

### Logout
GET  http://localhost:4000/common-api/logout